### PR TITLE
Level Saving System

### PR DESCRIPTION
**Pull request by TheSpartaGod**
1st iteration of saving system. Call using DataController.Instance.UpdateLevelData() and SaveSystem.SavePlayerData()

### CODE REVIEW

**Review by adhxll — CHANGES_REQUESTED** [review]
Scene files:
-

Controller files:
-
1. LevelSelectionController.cs 
=> the function SaveGame might be redundant, since you can just directly access the SaveSystem class. Consider deleting it.

Utilities files:
- 

1. PlayerData.cs  
=> still loading the default value for debugging purposes? So later, the parameter database is for the actual data?
2. SaveSystem.cs  
=> still saves the data right on the root path. Consider changing it to a designated folder for saving player’s data like “PlayerData/poloData.json” 
=> also, the file name is a bit confusing. Because it only saves level data, just change it into LevelData.json maybe? But any name is okay, as long as it represents what you’re saving 

Helper files:
- 
1. Please add the folder path that contains all of the future level data into .gitignore 

Framework / Library files (All the libraries used within this project are matched and based on the requirements):
-

Asset files:
-

Architecture:
-

Code convention & style:
-
1. There are still a lot of trailing newlines huh :D it’s okay, if there are no changes in this PR just fix it in the next commit (update: there are changes in this PR so do fix the trailing newlines hehe)
2. Due to the little details of this system, do add documentations that describe each class’ purpose. 

Performance / memory management:
- 
1. Just realized that the levelID has no stageID info. I think this is important to have when we have multiple stages and when u reference a levelId do refer to the stage id also. This is called composite keys (https://www.techopedia.com/definition/6572/composite-key)
2. Now after seeing the whole system closely, I’m pretty certain that it will be best to separate the JSON file (poloData) into each of its level. The reasons are as following:
 => if you see the DataController.cs, all of the function tries to search for the id that the function wants to edit. While searching, you need to iterate each time you want to do so and this isn’t very optimal. I think you can just turn the json file into a separate file.json and then store its name and levelID (because the levelID is often used to search a level) in a dictionary (https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-6.0) so you can just reference the levelID next time, and you’ll get the file.json.
  => so when making folders to save the files, you can separate each level with stage folders 
  => another alternative to dictionary variable is to just refer to the path of level data using its level id and stage id, for example if you want to access level 1 from stage 1, you can just refer to path “PlayerData/LevelData/Stage1/Level1

**Comment by TheSpartaGod** [comment]
**Controller files:**  
1. SaveGame masih gua pake untuk debugging karena dia gua taro di save button. Nanti kalo udah ada semua struktur datanya gua hapus kok
**Utilities files:** 
1. parameter database = DB of scriptable objects that contains non-mutable values i.e. songs, level name, midi file, etc. I use the parameter database to give each entry a "levelitemcontainer" class that stores mutable values i.e. score, highscore, starcount, etc. Default values are called when there are no save file. 
2. -Oke, nanti gua buat foldernya.
- rencananya gua naro juga achievements dan unlocked skins, jadi kyknya penamaannya gapapa
**Code Convention and style**
1. ok boss
2. ok boss
**Performance and memory management:** 
1. ok, i'll add stage. (rada belakangan yak, soalnya gua harus separate DB levels yang ada sekarang)
2. Menurut gw kyknya bakalan rada susah dan inefficient ngebagi data JSON ke per-stage, karena setiap kali pindah level bakalan harus deserialize/serialize si JSONnya menjadi object di C# dan harus read/write JSON berulang kali. Menurut gua lebih baik kita store semuanya di 1 JSON biar ada dedicated time untuk loading data (pas startup), terus store loaded data di RAM (sebagai object PlayerData) yang bisa kita utakatik dengan cepat (karena RAM itu much faster than storage), dan save ketika perlu. Untuk di DataController setelah gw cek lagi kyknya emang gak perlu bikin for loop jadi nanti gua ganti jadi lebih simple.

**Comment by adhxll** [comment]
OK, everything is clear except a few things:
1. pokoke i trust u buat manage kapan mau execute yang manaa jadi kabari ajah 👍🏻
2. Untuk pembagian data level ke tiap stage, itu yang gua maksud tetep nanti di load sekali, tapi instead of pakai array nanti bakal pakai dictionary yang memakai levelID dan stageID (which kalo 2 keysnya mungkin harus buat jadi string path sih) sebagai keys dictionarynya. Jadi di loadnya tetep sekali, but kita tetep bisa ngakalin strukturnya supaya ga perlu iterate ketika searching! But anyway my concern lies on the efficiency of database manipulationnya, jadi kalo di bagian logicnya bisa diakalin i think aman banget buat pake struktur global json kyk sekarang. U revise aja dulu menurut yang paling oke buat situasi sekarang, we can discuss more on monday :D

notes: database efficiency untuk sekarang juga belum urgent walaupun ada baiknya di set dari awal, apalagi kita cuma singleplayer dan datanya bentuknya gitu aja. Kalo punya prioritas lain ditinggal dulu pun gapapah tapi nanti ngomong dulu yakk

**Comment by TheSpartaGod** [comment]
Changes made
- Added saves folder, and updated gitignore.
- PlayerData now stores level data using Dictionary<int, LevelItemContainer> to store loaded data. Dictionaries can't be parsed into JSON using Unity's default JsonUtility, so we need a List<LevelItemContainer> to store it when saving / loading data. 
- Levels are stored inside of the dictionary using "stageID-levelID" as key, so stage 2 level 3 would be level 2-3. 
- Removed the island on level selection scene hierarchy, and changed it into a prefab. 
- Stages (islands) are stored as prefab. The new StageDatabase ScriptableObject stores the stage prefabs. Why prefab? because multiple GameObjects are on the island. 
- Stage 1 is bossa island, stage 2 is just for testing purposes and can be changed. 
- Added StageConstructor in LevelSelection to instantiate the prefabs based on the current stage
- ModalController and LevelSelectionController is now Singleton, but only inside of LevelSelection. This is to support multiple island prefabs, because each prefab cannot refer to an instantiated class in the scene hierarchy. 
Still TODO: 
- UI elements to change the island
- Actually changing the island in runtime, blom kepikiran cara yang enaknya gimana

**Comment by adhxll** [comment]
Scene files:
-

Controller files:
-
1. DataController.cs 
=> Function UnlockNewLevel.cs (line 70-75) doesn’t have an error handling for when the level is the last level (ex, if you’re calling the current level 5, there’s not going to be the next level to be unlocked). You can just only call this function when the last level is level 4, but it’s better to have the error handling at both. 
=> I think you can start using real values instead of dummy generated ones to test the flow of the .json and stuff. Any blockers? 

Utilities files:
-
1. Stages.cs 
=> From the name, I thought it was a stage object but it turns out it just contains an array of stages. Wouldn’t it be more suitable to put this list into a StageController class? But it turns out StageController class controls the levels inside a stage sih :”) Can you explain more on what Stages.cs was supposed to be other than a stages holder? If it’s necessary to have this class, it’s okk 

Helper files:
- 
1. I think it will be appropriate to have a public function where it takes the stageId and levelId as parameters and converts it into the dict keys, so you don’t have to manually make it each time you’re going to reference it. It serves as standardization and to prevent misspelling.

Framework / Library files (All the libraries used within this project are matched and based on the requirements):
-

Asset files:
-

Architecture:
-

Code convention & style:
-

Performance / memory management:
-
1. The performance is so much better!!! And you managed to only use one json fileee so yayyy

**Review by adhxll — APPROVED** [review]

**Pull request merged**
